### ISSUE TITLE
[Feature] 建议添加便携版

### ISSUE THREAD

**Issue by sephiroth945** [keiko233/clash-nyanpasu#1]
请求添加便携版，Webview可以自行安装，谢谢！

**Comment by keiko233** [comment]
便携版是有打包的，看上去是上传失败了，明天我看看

**Comment by iKun10001** [comment]
大佬牛逼  爱你

> 便携版是有打包的，看上去是上传失败了，明天我看看

**Comment by keiko233** [comment]
已修复 https://github.com/keiko233/clash-nyanpasu/commit/0c2e4fe34a4ae19d98a703ebbdcff99461c21211 ，并补充上传 https://github.com/keiko233/clash-nyanpasu/releases/download/v1.4.0/Clash.Nyanpasu_1.4.0_x64_portable.zip
