### ISSUE TITLE
[BUG] 初次订阅时使用 Clash Rust 内核无法切换 vmess 配置，先换其他核心切换配置后再切回即可

### ISSUE THREAD

**Issue by ericclose** [keiko233/clash-nyanpasu#107]
**Describe the bug**
初次订阅时使用 Clash Rust 内核无法切换配置，报错 `failed to put configs with status "501"`
**注意**：使用订阅链接为 vmess + websocket + TLS，应该为 clash 核心所支持协议

**To Reproduce**
复现过程:

1. **初始安装** 或 **移除配置文件夹** `%USERPROFILE%\.config` 和 `%USERPROFILE%\AppData\Local\moe.elaina.clash.nyanpasu`
2. 切换 Clash Rust 核心
3. 订阅 Remote 节点链接
4. 切换配置

**Expected behavior**
预期行为：
* 报错 `failed to put configs with status "501"`
* 只要**先使用其他核心**，然后**再切换配置**，**再切换成 Clash Rust** 就能正常使用。

**Screencast**

https://github.com/keiko233/clash-nyanpasu/assets/34526560/2afd1a9e-7d97-4929-aa04-7a9430a1c37a

**Information**

- OS: **Windows 11 Pro 23H2 22631.2715**
- Clash Nyanpasu Version: **1.4.1**
- Clash Core: **Clash Rust**

**Additional context**
日志：
[2023-12-12-0949.log](https://github.com/keiko233/clash-nyanpasu/files/13642781/2023-12-12-0949.log)

**Comment by ericclose** [comment]
#61 相同 issue

**Comment by greenhat616** [comment]
1、似乎是 `clash-rs` 的 API 兼容性问题。需要调查一下 rs 底层是否有不一致的地方。https://github.com/keiko233/clash-nyanpasu/blob/259e348e4d451a4fa4cbe7709f5a043ccfc06ea9/backend/tauri/src/core/clash_api.rs#L9-L26
* 可能关联的问题：https://github.com/Watfaq/clash-rs/issues/191
2、
![image](https://github.com/keiko233/clash-nyanpasu/assets/41122242/035adad4-c2c2-469a-bf22-421fcac2e634)
你可以在这里看到运行配置。这两个选项本质上只是对你导入的订阅配置再做一次修改后，使用核心启动该配置。

**Comment by ericclose** [comment]
> 1、似乎是 `clash-rs` 的 API 兼容性问题。需要调查一下 rs 底层是否有不一致的地方。
> 
> https://github.com/keiko233/clash-nyanpasu/blob/259e348e4d451a4fa4cbe7709f5a043ccfc06ea9/backend/tauri/src/core/clash_api.rs#L9-L26
> 
> * 可能关联的问题：[Missing Web api Watfaq/clash-rs#191](https://github.com/Watfaq/clash-rs/issues/191)
> 
> 2、 ![image](https://private-user-images.githubusercontent.com/41122242/289732872-035adad4-c2c2-469a-bf22-421fcac2e634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTMwNDQsIm5iZiI6MTcwMjM1Mjc0NCwicGF0aCI6Ii80MTEyMjI0Mi8yODk3MzI4NzItMDM1YWRhZDQtYzJjMi00NjlhLWJmMjItNDIxZmNhYzJlNjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAzNDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ODRiZDhiYWJhM2FhNTI0Nzg4YzA3OTFmMDkzODM2NDMyMGE3ZDA3Y2YwMDRlMWU0NzU2YjYyZjI4YmJmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPd8xsZ-4t3bYuirogbHmiIPR2BkITA8YxhRbYpWsOQ) 你可以在这里看到运行配置。这两个选项本质上只是对你导入的订阅配置再做一次修改后，使用核心启动该配置。

---

具体如何实现的我不知道，我可以确定的是直接使用 clash rust 核心，同样的配置可以使用的。就是通过初始配置的 clash-nyanpasu 的 clash rust 核心无法切换到配置，切换其他核心之后再切换回 clash rust 核心就可以了，api 兼容这些我不懂 😿

**Comment by greenhat616** [comment]
上游已经在 0.1.12 中支持了，这几日会提交个 PR 彻底修复此问题。

**Comment by xmh0511** [comment]
> 上游已经在 0.1.12 中支持了，这几日会提交个 PR 彻底修复此问题。

我现在用的0.1.13内核，切换后节点列表不会发生变化

**Comment by greenhat616** [comment]
> > 上游已经在 0.1.12 中支持了，这几日会提交个 PR 彻底修复此问题。
> 
> 我现在用的0.1.13内核，切换后节点列表不会发生变化

目前还没有修复，周末我看一下.

**Comment by ericclose** [comment]
问题已解决。
