### ISSUE TITLE
[Feature] 增加节点选择界面节点按钮的宽度

### ISSUE THREAD

**Issue by Taskeren** [keiko233/clash-nyanpasu#11]
**Is your feature request related to a problem? Please describe.**
当节点名字很长的时候会无法看到全部名字，拉长GUI也不行。

**Describe the solution you'd like**
增加节点按钮的宽度，或者添加列表视图。

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by keiko233** [comment]
这个可以有，也许未来会支持

**Comment by keiko233** [comment]
done. https://github.com/keiko233/clash-nyanpasu/commit/341f76fdc1498e2fa4732665a55fe8afaa02879e
