### ISSUE TITLE
软件经常会连接这个网站

### ISSUE THREAD

**Issue by QIU-XING** [keiko233/clash-nyanpasu#116]
![image](https://github.com/keiko233/clash-nyanpasu/assets/63764135/201b3cec-cbb4-40ff-b6b5-0a1400d0fe68)
日志里面看到这个时不时软件会连接 一下mirror.ghproxy.com:443，这是定期查找更新？？verge和CFW都没有这个连接。
[2023-12-07T16:54:41.3271826+08:00] [TCP] 127.0.0.1:53345(Clash Nyanpasu.exe) --> mirror.ghproxy.com:443 match Match using

**Comment by keiko233** [comment]
close. https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md
