### ISSUE TITLE
开tun模式节点延迟变高,一段时间后直接无法连接

### ISSUE THREAD

**Issue by bakasine** [keiko233/clash-nyanpasu#123]
### 复现步骤 / Step to reproduce

1.打开服务模式
2.打开tun
3.关闭tun打开系统代理 恢复正常情况

### 预期行为 / Expected behaviour

正常应该没区别

### 实际行为 / Actual Behaviour

更新1.4.1版本之前我都是使用系统代理模式, 最近才改成tun模式, 所有节点频繁出现失联和延迟爆高的情况
然后今天关闭tun和服务模式换回系统代理后延迟正常了

### 应用日志 / App logs

没有日志

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

不是

### 操作系统及版本 / OS version

windows11 23H2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
这个是内核的问题，请向 Clash Meta 或者 Clash RS 反馈（取决于你使用的内核）。
TUN 性能一直都很有问题，所以很多时候需要配合 passby 使用。
