### ISSUE TITLE
[Bug] 在 Proxies 中, 延迟大于 500 的 proxy 的数字的颜色有误

### ISSUE THREAD

**Issue by foobarjohnny** [keiko233/clash-nyanpasu#124]
### 复现步骤 / Step to reproduce

1. 在 Proxies 中, 点击 Delay Check 按钮.
2. 观察每个 Proxy 后面的数字

### 预期行为 / Expected behaviour

当 Proxy 能用, 只是延迟大于 500 时, 数字应该是 Warning Color(棕色)

### 实际行为 / Actual Behaviour

延迟大于 500 时, 数字变成了 Error Color (红色).

![image](https://github.com/keiko233/clash-nyanpasu/assets/11809464/a9ee3112-4758-4d34-bf1d-5857bb21963a)

### 备注 / Addition details

这个 Bug 我在旧版本的 Clash Verge 中已经提交过 https://github.com/zzzgydi/clash-verge/issues/836, 并且 Fix 了, 所以在这个作为其后续版本的 clash-nyanpasu 中不应该存在啊.

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

No

### 操作系统及版本 / OS version

Windows 10

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
已在 https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release 修复。
