### ISSUE TITLE
[BUG] MacOS “使用”配置报错

### ISSUE THREAD

**Issue by Jancat** [keiko233/clash-nyanpasu#16]
**Describe the bug**
新建配置后，点击**使用**后提示错误，无错误信息

**Expected behavior**
点击**使用**后激活代理

**Screenshots**
<img width="800" alt="image" src="https://github.com/keiko233/clash-nyanpasu/assets/11827786/f96940e8-36e3-46ae-b5ab-03abd3c3ad80">

**Information**

- OS: macOS 14.1.1 (M2)
- Clash Nyanpasu Version: 1.4.0

**Comment by keiko233** [comment]
需要提供日志文件诊断

**Comment by LaicZhang** [comment]
应该是当前版本不支持m系列芯片造成的，希望可以早点发布新版本

**Comment by keiko233** [comment]
> 应该是当前版本不支持m系列芯片造成的，希望可以早点发布新版本

https://github.com/keiko233/clash-nyanpasu/issues/3#issuecomment-1826352151
看这里

**Comment by Jancat** [comment]
@keiko233 
pre-release 下载的两个 dmg 都无法使用

[Clash Nyanpasu Dev](https://github.com/keiko233/clash-nyanpasu/releases/tag/dev)
<img width="936" alt="image" src="https://github.com/keiko233/clash-nyanpasu/assets/11827786/9e082640-0424-4825-a855-cd64748dbb82">


**arrch64.dmg**

<img width="260" alt="image" src="https://github.com/keiko233/clash-nyanpasu/assets/11827786/eeb2f7e2-6ae8-4acb-881e-9fcc2331e0d2">

**x64.dmg**

<img width="800" alt="image" src="https://github.com/keiko233/clash-nyanpasu/assets/11827786/0898b329-2fc3-4147-ab9f-c68d3eaeb16c">


```
2023-12-01 19:03:27 INFO - clash core terminated
2023-12-01 19:03:34 INFO - recover clash core
2023-12-01 19:03:34 ERROR - [clash]: This program can only be run on AMD64 processors with v3 microarchitecture support.
```

**Comment by keiko233** [comment]
可能是交叉编译出了问题，有空我看看

**Comment by ytai-chn** [comment]
文件损坏无法打开可以通过这个命令来跳过验证：
sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Nyanpasu.app
