### ISSUE TITLE
[功能请求] 给 Profiles 中的 Profile 添加拖拽功能.

### ISSUE THREAD

**Issue by foobarjohnny** [keiko233/clash-nyanpasu#164]
### 需求 / Requirement

给 Profiles 中的 Profile 添加拖拽功能.

### 建议实现 / Suggested implements

以前 Clash For Windows 支持对 Profiles 中的 Profile 进行拖拽来调整位置, 可供参考.

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

No

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
1.4.1 支持拖拽啊？

**Comment by foobarjohnny** [comment]
> 1.4.1 支持拖拽啊？

我刚刚重新下载并试了 1.4.1 的 Windows 和 macOS(ARM) 版, 都拖拽不了. 是要在 Settings 中有什么设置吗 ?

**Comment by greenhat616** [comment]
![image](https://github.com/keiko233/clash-nyanpasu/assets/41122242/fe4e22ad-dec6-4915-b08c-114d0787bf54)
对这个拖

**Comment by foobarjohnny** [comment]
原来如此, 攒 👍, 谢谢.
