### ISSUE TITLE
请问该项目与clash-verge-rev的关系

### ISSUE THREAD

**Issue by MerlinKodo** [keiko233/clash-nyanpasu#17]
看到clash-verge-rev中合并了该项目的很多修改，请问后续是两个项目独立开发，还是本项目由verge-rev继承？

**Comment by keiko233** [comment]
这个分支修改自clash verge，最初目的只是出于我自用修改的，对于其他事件我一概不知

**Comment by MerlinKodo** [comment]
好的 我还以为是这个项目转移到verge-rev开发了，看来并不是，那verge-rev有点不讲武德了。

**Comment by keiko233** [comment]
> 好的 我还以为是这个项目转移到verge-rev开发了，看来并不是，那verge-rev有点不讲武德了。

https://t.me/keikolog/465

后续看法我会发表到这里

**Comment by golovo** [comment]
我发现工作目录都是.config/clash-verge 有点奇怪，就查到了这里。容易让人误解。
