### ISSUE TITLE
nightly dev build failed

### ISSUE THREAD

**Issue by greenhat616** [keiko233/clash-nyanpasu#177]
### 复现步骤 / Step to reproduce

RT

### 预期行为 / Expected behaviour

Works as normal

### 实际行为 / Actual Behaviour

rocksdb builds failed

https://github.com/keiko233/clash-nyanpasu/actions/runs/7269625988

### 备注 / Addition details

related https://github.com/rust-rocksdb/rust-rocksdb/issues/776

### Clash Nyapasu 版本号 / Clash Nyapasu

latest

### 是否为 Pre-release / Is pre-release version

latest

### 操作系统及版本 / OS version

macos

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
并且在 win 下 WIX 的安装方式不支持非数字：
https://github.com/greenhat616/clash-nyanpasu/actions/runs/7272086663/job/19813652202

**Comment by greenhat616** [comment]
https://github.com/tauri-apps/tauri/issues/5286
Tauri 做的十分粗暴，根本不给 **workaround** 的机会

**Comment by greenhat616** [comment]
https://github.com/tauri-apps/tauri/issues/8038

NSIS 因为 tauri 的 bug 也无法完成编译，因此目前 windows 所有的 bundle 都只能用 workaround 处理了。

**Comment by keiko233** [comment]
good. 👍
