### ISSUE TITLE
 闪退

### ISSUE THREAD

**Issue by qhq** [keiko233/clash-nyanpasu#189]
### 复现步骤 / Step to reproduce

双击程序打开，托盘有图标，几秒后图标消失。任务管理器查看，clash是进程打开的。

### 预期行为 / Expected behaviour

一直显示

### 实际行为 / Actual Behaviour

图标消失

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

win11  Build25941.rs_prerelease.230825-1352

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Y4er** [comment]
同闪退

Clash Nyapasu 版本号 / Clash Nyapasu
1.4.2

是否为 Pre-release / Is pre-release version
否

操作系统及版本 / OS version
Microsoft Windows [版本 10.0.19045.3570]

**Comment by keiko233** [comment]
尝试重新下载安装，看看问题是否还存在

**Comment by qhq** [comment]
> 尝试重新下载最新打包的并安装，看看问题是否还存在

使用的是便携版，试过全部删除拖放

**Comment by qhq** [comment]
最新打包的问题解决。
