### ISSUE TITLE
更新1.4.2后Nyanpas闪退

### ISSUE THREAD

**Issue by ohhccwss** [keiko233/clash-nyanpasu#190]
### 复现步骤 / Step to reproduce

1.在1.41中检测更新
2.等待更新并安装完成
3.安装完成后自动打开新版本1.42，新版本的蓝色图标在托盘短暂出现后消失，任务管理器中有mihomo.exe和服务进程，但无法找到nyanpasu相关进程
4.手动打开nyanpasu仍然出现3中相同的现象

### 预期行为 / Expected behaviour

在托盘出现图标后一直存在

### 实际行为 / Actual Behaviour

短暂出现图标后消失

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 10 19045.3803

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by qwqxkii** [comment]
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎6/‎23
操作系统版本	22621.2861
体验	Windows Feature Experience Pack 1000.22681.1000.0
同样遇到更新1.4.2后Nyanpas闪退

**Comment by KyoSakuyo** [comment]
windows版本可以先回退到1.4.1版本之后，把内核切换到clash，再更新1.4.2之后，回切mihomo内核可以避免这个问题。

macOS依旧无解，上述方法无效

**Comment by greenhat616** [comment]
有办法可以获取到日记吗？
Windows 下在：`C:\Users\用户名\.config\clash-verge\logs`

**Comment by yanghl9898** [comment]
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2023/‎11/‎3
操作系统版本	22621.2715
1.4.2版本，最新的msi包，gui进程没了，但是clash verge服务还在

**Comment by ohhccwss** [comment]
@greenhat616 可以的，但是大部分都是空白的
[2023-12-25-1305.log](https://github.com/keiko233/clash-nyanpasu/files/13765150/2023-12-25-1305.log)
[2023-12-25-1308.log](https://github.com/keiko233/clash-nyanpasu/files/13765151/2023-12-25-1308.log)
[2023-12-25-1322.log](https://github.com/keiko233/clash-nyanpasu/files/13765152/2023-12-25-1322.log)
[2023-12-25-1359.log](https://github.com/keiko233/clash-nyanpasu/files/13765153/2023-12-25-1359.log)
按照@KyoSakuyo 的方法后可以正常运行，但是日志中出现了的乱码，且日志字体颜色显示为很不显眼的淡灰色，不知是新版本的设定还是另外的bug

**Comment by yanghl9898** [comment]
> 有办法可以获取到日记吗？ Windows 下在：`C:\Users\用户名\.config\clash-verge\logs`

2023-12-25 16:08:21 ERROR - invalid function "open_dashboard"
2023-12-25 16:08:22 INFO - running timer task `rGgPCxzslixC`
2023-12-25 16:08:30 ERROR - invalid function "open_dashboard"
2023-12-25 16:08:31 INFO - running timer task `rGgPCxzslixC`
2023-12-25 16:08:59 INFO - register hotkey CTRL+2 open_dashboard
2023-12-25 16:08:59 INFO - running timer task `rGgPCxzslixC`
2023-12-25 16:08:59 INFO - running timer task `rEt68cjKUCAS`
2023-12-25 16:08:59 ERROR - error sending request for url (https://fly.puroc.cc/api/v1/client/subscribe?token=5d07b72d616c14ea288bbd8feaa309c2): error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)
2023-12-25 16:08:59 ERROR - error sending request for url (https://panel.skrspc.com/api/v1/client/subscribe?token=187c39f97232aaacdfcff960036a4ee9&flag=metahy2): error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)
2023-12-25 16:09:00 ERROR - 系统找不到指定的文件。 (os error 2)
2023-12-25 16:09:00 ERROR - 系统找不到指定的文件。 (os error 2)
2023-12-25 16:44:59 INFO - reset proxy with no action

**Comment by yanghl9898** [comment]
按照@KyoSakuyo 的方法后可以正常运行，但是日志中出现了�的乱码，且日志字体颜色显示为很不显眼的淡灰色，不知是新版本的设定还是另外的bug
我按照他的方法都不行，还是只有服务，没有gui

**Comment by ningsibuqu** [comment]
一样 我把 .config\clash-verge 删了，就不闪退了

**Comment by S-T-eve** [comment]
破案了，直接升级之后，内核文件名变动（clash-meta->mihomo），但是配置文件里的内核调用字段没变更，所以gui报错了
解决办法很简单，打开应用目录里的verge.yaml文件，然后把`clash_core: clash-meta`改成`clash_core: mihomo`就好

**Comment by S-T-eve** [comment]
破案了，直接升级之后，内核文件名变动（clash-meta->mihomo），但是配置文件里的内核调用字段没变更，所以gui报错了
解决办法很简单，打开应用目录里的verge.yaml文件，然后把`clash_core: clash-meta`改成`clash_core: mihomo`就好

**Comment by ohhccwss** [comment]
> 破案了，直接升级之后，内核文件名变动（clash-meta->mihomo），但是配置文件里的内核调用字段没变更，所以gui报错了 解决办法很简单，打开应用目录里的verge.yaml文件，然后把`clash_core: clash-meta`改成`clash_core: mihomo`就好

这个方法我之前试过，也不行

**Comment by greenhat616** [comment]
方便试一下 Dev build 嘛？
https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release
https://github.com/keiko233/clash-nyanpasu/actions/runs/7321949191，刚刚把崩溃日记的收集加上去了。

**Comment by S-T-eve** [comment]
> > 破案了，直接升级之后，内核文件名变动（clash-meta->mihomo），但是配置文件里的内核调用字段没变更，所以gui报错了 解决办法很简单，打开应用目录里的verge.yaml文件，然后把`clash_core: clash-meta`改成`clash_core: mihomo`就好
> 
> 这个方法我之前试过，也不行

有没有别的因素（运行缓存什么之类的）不确定，因为我是直接升级之后GUI崩溃了，于是卸载了重新安装，但是又崩溃，于是从配置文件下手，然后根据@KyoSakuyo和@ningsibuqu的操作推断应该是版本变更后部分配置文件字段有问题，于是对照试了一下，确实当`clash_core: clash-meta`时会发生崩溃，手动改成`clash_core: mihomo`后崩了一次，然后配置文件自动发生变动（可能是读到内核后其他配置文件接着刷新了），之后就正常了
verge.yaml配置文件前后如下

前：
> # Clash Nyanpasu Config
> 
> app_singleton_port: null
> app_log_level: trace
> language: zh
> theme_mode: system
> theme_blur: false
> traffic_graph: true
> enable_memory_usage: true
> page_transition_animation: none
> enable_tun_mode: false
> enable_service_mode: false
> enable_auto_launch: false
> enable_silent_start: false
> enable_system_proxy: false
> enable_proxy_guard: false
> system_proxy_bypass: |-
>   localhost
>   127.*
>   10.*
>   172.16.*
>   172.17.*
>   172.18.*
>   172.19.*
>   172.20.*
>   172.21.*
>   172.22.*
>   172.23.*
>   172.24.*
>   172.25.*
>   172.26.*
>   172.27.*
>   172.28.*
>   172.29.*
>   172.30.*
>   172.31.*
>   192.168.*
>   <local>
>   *.cn
>   *.qq.com
>   *.sogou.com
> proxy_guard_duration: 30
> theme_setting:
>   primary_color: null
>   secondary_color: null
>   primary_text: null
>   secondary_text: null
>   info_color: null
>   error_color: null
>   warning_color: null
>   success_color: null
>   font_family: null
>   css_injection: null
>   page_transition_duration: null
> web_ui_list: null
> clash_core: clash-meta
> hotkeys: null
> auto_close_connection: true
> default_latency_test: http://www.google.com/generate_204
> enable_clash_fields: false
> enable_builtin_enhanced: true
> proxy_layout_column: 6
> window_size_position:
> - 1145.0
> - 716.0
> - 357.0
> - 258.0
> enable_random_port: false
> verge_mixed_port: 7899
> 

后：

> # Clash Nyanpasu Config
> 
> app_singleton_port: null
> app_log_level: trace
> language: zh
> theme_mode: system
> theme_blur: false
> traffic_graph: true
> enable_memory_usage: true
> page_transition_animation: none
> enable_tun_mode: false
> enable_service_mode: false
> enable_auto_launch: false
> enable_silent_start: false
> enable_system_proxy: true
> enable_proxy_guard: false
> system_proxy_bypass: |-
>   localhost
>   127.*
>   10.*
>   172.16.*
>   172.17.*
>   172.18.*
>   172.19.*
>   172.20.*
>   172.21.*
>   172.22.*
>   172.23.*
>   172.24.*
>   172.25.*
>   172.26.*
>   172.27.*
>   172.28.*
>   172.29.*
>   172.30.*
>   172.31.*
>   192.168.*
>   <local>
>   *.cn
>   *.qq.com
>   *.sogou.com
> proxy_guard_duration: 30
> theme_setting:
>   primary_color: null
>   secondary_color: null
>   primary_text: null
>   secondary_text: null
>   info_color: null
>   error_color: null
>   warning_color: null
>   success_color: null
>   font_family: null
>   css_injection: null
>   page_transition_duration: null
> web_ui_list: null
> clash_core: mihomo
> hotkeys: null
> auto_close_connection: true
> default_latency_test: http://www.google.com/generate_204
> enable_clash_fields: false
> enable_builtin_enhanced: true
> proxy_layout_column: 6
> auto_log_clean: null
> window_size_position:
> - 1145.0
> - 716.0
> - 357.0
> - 258.0
> window_size_state:
>   width: 1097.0
>   height: 717.0
>   x: 493.0
>   y: 279.0
>   maximized: false
>   fullscreen: false
> enable_random_port: false
> verge_mixed_port: 7899
>

**Comment by greenhat616** [comment]
应该和 mihomo 关系不是特别大，https://github.com/keiko233/clash-nyanpasu/blob/f23eb738521443856746fe55ba2ee3cc35748aa0/backend/tauri/src/config/verge.rs#L6-L16

这里是有做处理的。

我个人推测和 rocksdb 的创建问题有关系，那里使用了 unwrap。

**Comment by greenhat616** [comment]
> 按照@KyoSakuyo 的方法后可以正常运行，但是日志中出现了�的乱码，且日志字体颜色显示为很不显眼的淡灰色，不知是新版本的设定还是另外的bug

全灰是 bug，解决这个问题后会修复。包含“�”的乱码日记，之前提供的日记文件包含在内嘛

**Comment by ohhccwss** [comment]
> > 按照@KyoSakuyo 的方法后可以正常运行，但是日志中出现了�的乱码，且日志字体颜色显示为很不显眼的淡灰色，不知是新版本的设定还是另外的bug
> 
> 全灰是 bug，解决这个问题后会修复。包含“�”的乱码日记，之前提供的日记文件包含在内嘛

有的，在1359那个日志里

**Comment by ohhccwss** [comment]
> @KyoSakuyo @ohhccwss @CYNIC448 @qwqxkii
> 
> 方便试一下 Dev build 嘛？ https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release https://github.com/keiko233/clash-nyanpasu/actions/runs/7321949191 ，刚刚把崩溃日记的收集加上去了#191 。

这个版本使用msi覆盖1.4.1安装，重启电脑后可以正常运行

**Comment by S-T-eve** [comment]
> > > 破案了，直接升级之后，内核文件名变动（clash-meta->mihomo），但是配置文件里的内核调用字段没变更，所以gui报错了 解决办法很简单，打开应用目录里的verge.yaml文件，然后把`clash_core: clash-meta`改成`clash_core: mihomo`就好
> > 
> > 
> > 这个方法我之前试过，也不行
> 
> 有没有别的因素（运行缓存什么之类的）不确定，因为我是直接升级之后GUI崩溃了，于是卸载了重新安装，但是又崩溃，于是从配置文件下手，然后根据@KyoSakuyo和@ningsibuqu的操作推断应该是版本变更后部分配置文件字段有问题，于是对照试了一下，确实当`clash_core: clash-meta`时会发生崩溃，手动改成`clash_core: mihomo`后崩了一次，然后配置文件自动发生变动（可能是读到内核后其他配置文件接着刷新了），之后就正常了

好的，刚刚坚持了很久之后又崩了，之后又是连续崩，确实不行
卸载后保留配置回滚4dbe309（1.4.1）exe安装后，用pre-release-f23eb73的exe安装，目前使用正常
另外提一嘴，资源那里添加了规则集更新，能不能把geo更新也加进去

**Comment by S-T-eve** [comment]
刚刚pre-release报错弹窗并崩溃
![image](https://github.com/keiko233/clash-nyanpasu/assets/53549980/70870020-c13d-4762-94ae-ef053ddefe7e)
[2023-12-25-2250.log](https://github.com/keiko233/clash-nyanpasu/files/13766650/2023-12-25-2250.log)

**Comment by greenhat616** [comment]
那可以确定是 rocksdb 的问题了，我稍晚修复一下。

**Comment by greenhat616** [comment]
> > > > 破案了，直接升级之后，内核文件名变动（clash-meta->mihomo），但是配置文件里的内核调用字段没变更，所以gui报错了 解决办法很简单，打开应用目录里的verge.yaml文件，然后把`clash_core: clash-meta`改成`clash_core: mihomo`就好
> 
> > > 
> 
> > > 
> 
> > > 这个方法我之前试过，也不行
> 
> > 
> 
> > 有没有别的因素（运行缓存什么之类的）不确定，因为我是直接升级之后GUI崩溃了，于是卸载了重新安装，但是又崩溃，于是从配置文件下手，然后根据@KyoSakuyo和@ningsibuqu的操作推断应该是版本变更后部分配置文件字段有问题，于是对照试了一下，确实当`clash_core: clash-meta`时会发生崩溃，手动改成`clash_core: mihomo`后崩了一次，然后配置文件自动发生变动（可能是读到内核后其他配置文件接着刷新了），之后就正常了
> 
> 
> 
> 好的，刚刚坚持了很久之后又崩了，之后又是连续崩，确实不行
> 
> 卸载后保留配置回滚4dbe309（1.4.1）exe安装后，用pre-release-f23eb73的exe安装，目前使用正常
> 
> 另外提一嘴，资源那里添加了规则集更新，能不能把geo更新也加进去

https://github.com/keiko233/clash-nyanpasu/issues/49 geo 更新被安排在这个 issue 里了。 mihomo 目前内核支持geo 更新，但是其他内核还没有。需要调研一下 rs 的情况，才好动手。

**Comment by greenhat616** [comment]
可以试一下今天早上九点左右会自动构建的测试版，看看能否解决这个问题。

**Comment by CYNIC448** [comment]
> 可以试一下今天早上九点左右会自动构建的测试版，看看能否解决这个问题。

[Clash.Nyanpasu_1.4.2-alpha+2e27c9a_x64，这个版本解决了

**Comment by ohhccwss** [comment]
> 可以试一下今天早上九点左右会自动构建的测试版，看看能否解决这个问题。

 早上更新到现在一切正常

**Comment by S-T-eve** [comment]
挂了一下午，从2023-12-26 15:19:15挂到2023-12-26 19:09:33，无崩溃，无明显特殊ERROR
不过发现了其他问题，我另开个issues

**Comment by chen-jingliang** [comment]
mac版升级到最新版后，闪退。

**Comment by greenhat616** [comment]
> mac版升级到最新版后，闪退。

是使用最新的开发测试版吗？是的话，能否将崩溃对话框 以及 日记贴在这个 issue 内呢？

**Comment by chen-jingliang** [comment]
> > mac版升级到最新版后，闪退。
> 
> 是使用最新的开发测试版吗？是的话，能否将崩溃对话框 以及 日记贴在这个 issue 内呢？

使用dev版本后正常，目前的1.4.2版本是否为修正版？

**Comment by greenhat616** [comment]
> > > mac版升级到最新版后，闪退。
> 
> > 
> 
> > 是使用最新的开发测试版吗？是的话，能否将崩溃对话框 以及 日记贴在这个 issue 内呢？
> 
> 
> 
> 使用dev版本后正常，目前的1.4.2版本是否为修正版？

否，解决 rust1.75 导致的 bug 后，将尽快发布 1.4.3。

**Comment by CiaranYoung** [comment]
win11相同的闪退问题，退回到1.41版本就正常了

**Comment by greenhat616** [comment]
尽快发布吧

**Comment by xiaochency** [comment]
我也遇到了这个问题

**Comment by HumanMus1c** [comment]
最新发行版1.4.4版本仍然启动瞬间闪退
[2024-01-30-1526.log](https://github.com/keiko233/clash-nyanpasu/files/14094269/2024-01-30-1526.log)
[2024-01-27-1456.log](https://github.com/keiko233/clash-nyanpasu/files/14094270/2024-01-27-1456.log)
[2024-01-26-1422.log](https://github.com/keiko233/clash-nyanpasu/files/14094271/2024-01-26-1422.log)
[2024-01-21-0010.log](https://github.com/keiko233/clash-nyanpasu/files/14094272/2024-01-21-0010.log)

**Comment by HumanMus1c** [comment]
![image](https://github.com/keiko233/clash-nyanpasu/assets/46023154/845d2cc0-53a8-40ad-ae10-efb9c6a15486)

**Comment by greenhat616** [comment]
请新开 issue。以及，请确认你使用的确实是 1.4.4。 1.4.3 以上崩溃显然会包含一个崩溃提示框，你可以观察这个 issue 的早前一个对预览版本的反馈，都是包含一个崩溃提示框的。

另，我观察到你新反馈了个图片，图片里清晰得提示了你目前使用的喵帕斯版本是 1.4.2。

谢谢。
