### ISSUE TITLE
[Feature] 考虑更新clash meta内核到最新的虚空终端版本

### ISSUE THREAD

**Issue by MerlinKodo** [keiko233/clash-nyanpasu#20]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Clash.Meta内核更名为虚空终端转入非公开开发，是否考虑更新内核至最新版本，或者添加一个新的虚空终端切换选项支持

文档地址：

https://wiki.metacubex.one/

二进制下载地址:

https://github.com/MerlinKodo/akasha-terminal-bin/releases/tag/latest

版本信息打印：

![image](https://github.com/keiko233/clash-nyanpasu/assets/150133030/34a6d628-fe1c-40dd-8482-6960aaf72921)

**Describe alternatives you've considered**

**Additional context**

**Comment by keiko233** [comment]
LGTM. Pined.

**Comment by fyhzc** [comment]
楼上两位大佬，支持合作。

**Comment by fyhzc** [comment]
可以观察三个月，要是clash和clash.meta两位原大佬不再更新。那就只用虚空终端吧。

**Comment by fyhzc** [comment]
实话说，有时三个选择很痛苦的。嘻嘻

**Comment by MerlinKodo** [comment]
> 可以观察三个月，要是clash和clash.meta两位原大佬不再更新。那就只用虚空终端吧。

虚空终端就是meta原作者在更新，只是为了规避风险改名和转到私有库了

**Comment by fyhzc** [comment]
膜拜大佬，学习大佬，成为大佬，超越大佬。

**Comment by fyhzc** [comment]
还有要通知一下，v2rayN的作者大佬，让他也跟进。

**Comment by imkiva** [comment]
> > 可以观察三个月，要是clash和clash.meta两位原大佬不再更新。那就只用虚空终端吧。
> 
> 虚空终端就是meta原作者在更新，只是为了规避风险改名和转到私有库了

请问曾经为 Clash.Meta 贡献过 [代码 PR](https://github.com/MetaCubeX/Clash.Meta/pulls?q=is%3Apr+author%3Aimkiva) 的可否加入该私有仓库呢？由于之前是开源项目，出于安全原因并不敢太频繁提交代码，如今成为了私有项目，倒是没有这些顾虑了。本人的代码能力不用担心，可以看我主页仓库的质量，希望能考虑本人的请求，感谢~

**Comment by leic4u** [comment]
> > > 可以观察三个月，要是clash和clash.meta两位原大佬不再更新。那就只用虚空终端吧。
> > 
> > 
> > 虚空终端就是meta原作者在更新，只是为了规避风险改名和转到私有库了
> 
> 请问曾经为 Clash.Meta 贡献过 [代码 PR](https://github.com/MetaCubeX/Clash.Meta/pulls?q=is%3Apr+author%3Aimkiva) 的可否加入该私有仓库呢？由于之前是开源项目，出于安全原因并不敢太频繁提交代码（只是由于个人不得不使用的功能的缺失才提交 PR），如今成为了私有项目，倒是没有这些顾虑了。本人的代码/工程能力不用担心，可以看我主页仓库的质量，希望能考虑本人的请求，感谢~

担心的话可以注册个小号来 PR 试试🫡
