### ISSUE TITLE
关于Mixin功能

### ISSUE THREAD

**Issue by sdh1986** [keiko233/clash-nyanpasu#201]
### 需求 / Requirement

是否能添加Mixin功能，就和原来Clash for windows 那样可以在启动软件时覆盖已有配置，而不是直接修改文件本身。或者说如何能达到这个效果，我找了几个类似的软件都没有找到相应功能，可能是我找的方式不对，如果已有请告知如何设置，谢谢。

### 建议实现 / Suggested implements

![20221226230540](https://github.com/keiko233/clash-nyanpasu/assets/31507699/02ee1a5d-209d-4483-bc13-0d4a9d1dc001)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

26f05a0

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
https://github.com/keiko233/clash-nyanpasu/issues/63#issuecomment-1846447256

**Comment by sdh1986** [comment]
感谢大佬，但是我发现就算修改了它还是会识别到我本地网卡设置的DNS，我记得 Clash For Windows 修改后它可以忽略本地网卡使用的DNS转而使用mixin里面配置的DNS，换句话说软件劫持了本地网卡获取的DNS非常神奇，但是目前这个项目我不知道如何实现这个功能，我直接用了大佬给出的文档对原订阅配置文件修改DNS也不行，它还是定位到了我的网卡DNS。

**Comment by sdh1986** [comment]
OK，谢谢大佬。
