### ISSUE TITLE
需求，是否考虑可以添加覆盖本地网卡DNS的功能

### ISSUE THREAD

**Issue by sdh1986** [keiko233/clash-nyanpasu#204]
### 需求 / Requirement

我记得 Clash For Windows 修改后它可以忽略本地网卡使用的DNS转而使用mixin里面配置的DNS，换句话说软件劫持了本地网卡获取的DNS非常神奇，但是目前这个项目我不知道如何实现这个功能，我直接用了大佬给出的文档对原订阅配置文件修改DNS也不行，它还是定位到了我的网卡DNS，现在就是想如何通过软件配置的DNS达到DNS解析而不是使用本地网卡中的DNS解析。

### 建议实现 / Suggested implements

![Snipaste_2023-12-27_14-56-32](https://github.com/keiko233/clash-nyanpasu/assets/31507699/da8d01cc-befd-44c2-86d7-bca517d83aad)
如果可以，想实现Clash for windows 类似这个功能。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

26f05a0

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by S-T-eve** [comment]
你是说Mixin功能吗，在这里是靠创建Merge类型配置文件来操作
直接配置页新建Merge，双击配置进编辑然后把dns字段内容填进去，会覆盖原始订阅的同字段内容（要先去设置->clash字段里把对应字段勾选，或者干脆去设置->杂项设置里把 开启字段过滤 关掉）
另外按理来说走core的流量也不太可能发给系统填的dns，除非你机场提供方压根没写dns规则

**Comment by sdh1986** [comment]
> 你是说Mixin功能吗，在这里是靠创建Merge类型配置文件来操作 直接配置页新建Merge，双击配置进编辑然后把dns字段内容填进去，会覆盖原始订阅的同字段内容（要先去设置->clash字段里把对应字段勾选，或者干脆去设置->杂项设置里把 开启字段过滤 关掉） 另外按理来说走core的流量也不太可能发给系统填的dns，除非你机场提供方压根没写dns规则

感谢，成功了，之前可能我的理解有误，谢谢大佬。
