### ISSUE TITLE
新版任务栏菜单闪退

### ISSUE THREAD

**Issue by lgf4591** [keiko233/clash-nyanpasu#206]
### 复现步骤 / Step to reproduce

点击程序后菜单栏出现后马上闪退

### 预期行为 / Expected behaviour

点击程序后菜单栏出现后马上闪退

### 实际行为 / Actual Behaviour

点击程序后菜单栏出现后马上闪退

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

1.4.2

### 操作系统及版本 / OS version

Win11 23H2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Yuan84** [comment]
任务栏图标消失，但是可以上网，不知道怎么回事

**Comment by zh-plus** [comment]
win11-22621.2861同样出现此bug

**Comment by S-T-eve** [comment]
> 任务栏图标消失，但是可以上网，不知道怎么回事

gui崩了，但是core还在后台运行，应该是和 #190 一样的问题
用dev build吧[https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release](https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release)

**Comment by greenhat616** [comment]
@S-T-eve Dev build 无了。因为 https://github.com/keiko233/clash-nyanpasu/issues/210 🥲

**Comment by S-T-eve** [comment]
> @S-T-eve Dev build 无了。因为 #210 🥲

啊？
那。。要么先用回[https://github.com/keiko233/clash-nyanpasu/releases/tag/v1.4.1](https://github.com/keiko233/clash-nyanpasu/releases/tag/v1.4.1)，
要么崩就崩了反正core没掉，配置文件把`external-controller: 127.0.0.1:9090`字段写上然后用[https://d.metacubex.one/](https://d.metacubex.one/)控制节点切换凑合用着先吧🤣
另外在dev挂掉前的v1.4.2-alpha+5cd919e #197 问题还是没修好

**Comment by greenhat616** [comment]
> > @S-T-eve Dev build 无了。因为 #210 🥲
> 
> 
> 
> 啊？
> 
> 那。。要么先用回[https://github.com/keiko233/clash-nyanpasu/releases/tag/v1.4.1](https://github.com/keiko233/clash-nyanpasu/releases/tag/v1.4.1)，
> 
> 要么崩就崩了反正core没掉，配置文件把`external-controller: 127.0.0.1:9090`字段写上然后用[https://d.metacubex.one/](https://d.metacubex.one/)控制节点切换凑合用着先吧🤣
> 
> 另外在dev挂掉前的v1.4.2-alpha+5cd919e #197 问题还是没修好

pr还没合进去

**Comment by Cluxifa** [comment]
limux版也这样，乌班图桌面系统。

**Comment by greenhat616** [comment]
试一下 `pre-release`：https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release

**Comment by Yuan84** [comment]
是的，已经在用

**Comment by SUGARYOUNGG** [comment]
直接闪退
