### ISSUE TITLE
[BUG]WIN客户端UI界面显示不正常！

### ISSUE THREAD

**Issue by wei727** [keiko233/clash-nyanpasu#21]
![截图20231126143752](https://github.com/keiko233/clash-nyanpasu/assets/81148177/2cebec4b-eda8-4b13-8792-49283aebc41a)
哪位大佬知道这是怎么回事啊，之前都没这情况突然一天打开软件UI界面就成这样了。。。。

**Comment by keiko233** [comment]
这里不是clash verge rev的issues

**Comment by wei727** [comment]
> 这里不是clash verge rev的issues

不好意思我偷懒了，我也装了你的客户端也是这种。所以就没有另外截图了！
