### ISSUE TITLE
`delay-timer` 在 Rust v1.75 下编译失败

### ISSUE THREAD

**Issue by greenhat616** [keiko233/clash-nyanpasu#210]
### 复现步骤 / Step to reproduce

https://github.com/BinChengZhao/delay-timer/issues/48
https://github.com/rust-lang/rust/pull/100806#issuecomment-1825585534
https://github.com/rust-lang/rust/pull/100806#issuecomment-1872295820

由于 Rust 的 Bug 被错误发行到 Stable channel 中了，因此造成 delay-timer 依赖的 `split_inclusive` 的类型推断错误。

因此，目前有两个解决方案：
* CI 锁定 1.74.1 - 等待 Rust 上游修复后，再切换 stable channel；
* 应用我之前写的 workaround，但是 CI 必须切 nightly，等待上游修复后且回来

### 预期行为 / Expected behaviour

正常工作

### 实际行为 / Actual Behaviour

略

### Clash Nyapasu 版本号 / Clash Nyapasu

所有

### 是否为 Pre-release / Is pre-release version

所有

### 操作系统及版本 / OS version

所有

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
cc @keiko233

**Comment by dyxushuai** [comment]
related https://github.com/rust-lang/rust/issues/100756
