### ISSUE TITLE
内置编辑器的段落折叠箭头显示错误

### ISSUE THREAD

**Issue by S-T-eve** [keiko233/clash-nyanpasu#212]
### 复现步骤 / Step to reproduce

null

### 预期行为 / Expected behaviour

类似于vsc
![image](https://github.com/keiko233/clash-nyanpasu/assets/53549980/d4795980-a259-4a99-9447-bec63ee9e4bc)

### 实际行为 / Actual Behaviour

![image](https://github.com/keiko233/clash-nyanpasu/assets/53549980/a1b98de1-cac5-4a65-a6ff-6f78b484e819)

### Clash Nyapasu 版本号 / Clash Nyapasu

v1.4.2-alpha

### 是否为 Pre-release / Is pre-release version

5cd919e

### 操作系统及版本 / OS version

Windows 10.0.19045.3803

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
`pre-release` 已修复

**Comment by S-T-eve** [comment]
确认已修复
