### ISSUE TITLE
希望托盘图标颜色跟随系统代理状态改变

### ISSUE THREAD

**Issue by Liyulive** [keiko233/clash-nyanpasu#219]
### 需求 / Requirement

希望托盘图标可以像cfw和clash verge那样在开启系统代理之后更换颜色，可以直观区分系统代理是否为开启状态。

### 建议实现 / Suggested implements

如clash verge，未开启系统代理时
![image](https://github.com/keiko233/clash-nyanpasu/assets/28747829/e5dd59ce-70f1-491d-be7c-50ba4aaf95cd)
开启系统代理之后
![image](https://github.com/keiko233/clash-nyanpasu/assets/28747829/7bfe7230-dccb-4b35-b7ba-62953915670e)

### 备注 / Addition details

我注意到在#188 中他的托盘图标有两种不同颜色，并且我在使用Clash Nyapasu中，在开启系统代理时代理托盘图标会闪烁一下，但并未有其他变化，所以我不清楚是没有此功能还是说我这出了bug。
此外并未使用 Pre-release 版本测试，不会编译，抱歉。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

517e166

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release 的预构建版本在这里获取。

Windows 下普通模式，Tun 模式，System Proxy 都有不同的托盘状态的。

**Comment by Liyulive** [comment]
感谢回复。
由于我以前的配置文件tun模式一直常开所以没有发现，是我的问题。
不过在tun模式下切换系统代理，托盘图标则不会发生变化，请问是否可以添加此项功能。
![ezgif com-video-to-gif-converter](https://github.com/keiko233/clash-nyanpasu/assets/28747829/41eec38f-d71d-4fb7-9625-01359812820d)

**Comment by greenhat616** [comment]
开启 Tun 的情况下，没有必要打开系统代理的。Tun 会劫持网卡流量。

**Comment by Liyulive** [comment]
好的谢谢，涨姿势了。

**Comment by magicianlib** [comment]
> https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release 的预构建版本在这里获取。
> 
> Windows 下普通模式，Tun 模式，System Proxy 都有不同的托盘状态的。

mac 系统没有这个效果
