### ISSUE TITLE
[BUG]kali系统没办法使用吗，打开一直白屏或者无ui

### ISSUE THREAD

**Issue by Wwllin** [keiko233/clash-nyanpasu#22]
安装包的版本是clash-nyanpasu_1.4.0_amd64.deb
系统是kali-linux-2023.3-vmware-amd64（在官网下载的虚拟机版本）
![1](https://github.com/keiko233/clash-nyanpasu/assets/150108125/35dae835-9e45-4bdc-a057-c9e4d3e2ca2f)
![2](https://github.com/keiko233/clash-nyanpasu/assets/150108125/6dc55713-1373-47d7-ac99-22ea0660a9fd)
![3](https://github.com/keiko233/clash-nyanpasu/assets/150108125/6c034dab-1b66-4d07-a813-efc3ace2b1e9)

**Comment by keiko233** [comment]
首先，不清楚kali，我在kde和gnome测试均表现良好，需要自行检查桌面环境。
其次，看你这个大概是内核没起来，请根据日志进行排错

**Comment by Wwllin** [comment]
> 首先，不清楚kali，我在kde和gnome测试均表现良好，需要自行检查桌面环境。 其次，看你这个大概是内核没起来，请根据日志进行排错。 最后，提issue需要按照模板，谢谢

不好意思，第一次提问😥
