### ISSUE TITLE
窗体拖拽位置和调整大小存在触发区不明确问题

### ISSUE THREAD

**Issue by S-T-eve** [keiko233/clash-nyanpasu#227]
### 复现步骤 / Step to reproduce

在试图调整窗体大小时，由于拖拽改变位置的触发区与窗体边界重合（过于接近），导致经常点不准然后变成移动窗体，偶然甚至能看到鼠标指针已经变成调整大小双箭头但是激活了窗体位置拖拽的情况

### 预期行为 / Expected behaviour

拖拽窗体是拖拽窗体，调整大小是调整大小，触发区要明确分开

### 实际行为 / Actual Behaviour

![动画](https://github.com/keiko233/clash-nyanpasu/assets/53549980/187707f6-86bb-4a07-b04d-f5514de4d6bc)

### 备注 / Addition details

可以的话就干脆把拖拽窗体的触发区限制在标题栏范围内，调整大小限制在窗体边界8px左右范围
如图
![2024-01-02 15-29-29 mp4_20240102_211654 746](https://github.com/keiko233/clash-nyanpasu/assets/53549980/d2a7f9c4-df67-405c-b0c5-226a1dcaa408)

### Clash Nyapasu 版本号 / Clash Nyapasu

v1.4.2-alpha

### 是否为 Pre-release / Is pre-release version

8b3e420

### 操作系统及版本 / OS version

Windows 10.0.19045.3803

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
pre-release构建已解决
