### ISSUE TITLE
No prompt when importing a wrong configuration from url

### ISSUE THREAD

**Issue by xmh0511** [keiko233/clash-nyanpasu#247]
### 复现步骤 / Step to reproduce

importing wrong formatted yaml configuration

### 预期行为 / Expected behaviour

prompt the error message

### 实际行为 / Actual Behaviour

 no prompt

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

macOs12

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [ ] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [ ] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [ ] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
是有提示的. 目前无法复现这个问题，可以提供一个示例吗？

另，你是不是开启了 windows 的勿扰模式、打开了勿扰模式将静默所有通知.

**Comment by xmh0511** [comment]
> 是有提示的. 目前无法复现这个问题，可以提供一个示例吗？
> 
> 另，你是不是开启了 windows 的勿扰模式、打开了勿扰模式将静默所有通知.

My system is macOS and I have given the prompt permission to clash. You just type `http://127.0.0.1:8080` into the config file link input and click the `import` button, there is no reaction.

**Comment by xmh0511** [comment]
https://github.com/keiko233/clash-nyanpasu/assets/17973891/bd9b25e4-b6f2-4c0a-b293-1cb5ee2a439f

Check the issue in this video

**Comment by greenhat616** [comment]
we use system notification API this time. Did you enable the mute  mode in your macOS controller center?

**Comment by xmh0511** [comment]
> we use system notification API this time. Did you enable the mute mode in your macOS controller center?

Of course, enable. I can see a "Refresh Clash Config" notification, so this issue cannot be caused by the reason you said it.

**Comment by greenhat616** [comment]
It seems to be fixed in v1.4.3. So I am closing it now. Feel free to open another issue if this issue is still exist.
