### ISSUE TITLE
添加“切换代理后自动断开旧连接”功能

### ISSUE THREAD

**Issue by S-T-eve** [keiko233/clash-nyanpasu#258]
### 需求 / Requirement

虽然目前在“连接”页里有“关闭全部”按钮，不过好像还是不太方便，可以的话还是需要添加整一个类似于cfw/metacubexd/yacd的“自动断开旧链”开关

### 建议实现 / Suggested implements

![image](https://github.com/keiko233/clash-nyanpasu/assets/53549980/fe26a3bc-c5df-4c3c-800e-8c92c89453d7)
![image](https://github.com/keiko233/clash-nyanpasu/assets/53549980/da05697b-d03d-4528-9350-5b2f0578d1f0)

### Clash Nyapasu 版本号 / Clash Nyapasu

v1.4.2-alpha

### 是否为 Pre-release / Is pre-release version

35d5296

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by ningsibuqu** [comment]
已经有这个功能了阿 你是说加个开关吗

**Comment by S-T-eve** [comment]
> 已经有这个功能了阿 你是说加个开关吗

重新翻了一下全部设置，是“设置”页的“杂项”里的“自动关闭连接”吗？那个我开着但是好像有时候切了节点但是感觉旧链没断开，搞得我还以为没这功能
回头再细看是不是有别的问题
