### ISSUE TITLE
希望增加Clash For Windows的Parsers功能

### ISSUE THREAD

**Issue by zz203203zhang** [keiko233/clash-nyanpasu#271]
### 需求 / Requirement

希望增加Clash For Windows的Parsers功能，机场订阅更新时，可以根据自定义Parsers进行规则匹配，这个功能很实用，尤其是面对有多个域名规则手动匹配时，很好用

### 建议实现 / Suggested implements

建议实现Clash For Windows的Parsers功能
![Snipaste_2024-01-16_09-17-42](https://github.com/keiko233/clash-nyanpasu/assets/22047391/eac2fcd4-6e78-4e3e-a76e-b076a3a7efe5)
![Snipaste_2024-01-16_09-17-13](https://github.com/keiko233/clash-nyanpasu/assets/22047391/2f434831-348e-4489-946a-0a3f43b81f4f)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

517e166

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请使用 merge 或者 scripts 替代
