### ISSUE TITLE
建议新建单独分支存放内核更新 manifest

### ISSUE THREAD

**Issue by aviraxp** [keiko233/clash-nyanpasu#289]
### 复现步骤 / Step to reproduce

检查 Clash 内核更新

### 预期行为 / Expected behaviour

正常更新

### 实际行为 / Actual Behaviour

![image](https://github.com/keiko233/clash-nyanpasu/assets/18079988/3dd79c9c-97ee-42e3-8d8c-6141424ae471)

### 应用日志 / App logs

无需日志

### 备注 / Addition details

[这里](https://github.com/keiko233/clash-nyanpasu/commit/12fc6951cb62feea59641f8b8a6e2e5e240a3b30#diff-4e7c71ce1a8eba3091c601c526025651d839df8388b683932931f5368d616884R298)写死了 json 文件地址，但是目前 dev 分支被删除了。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.3

### 是否为 Pre-release / Is pre-release version

20bc733

### 操作系统及版本 / OS version

Windows 11

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
已确认，稍晚恢复 dev 分支直到下一个版本发布。

**Comment by greenhat616** [comment]
之后应该会讨论一个 manifest v1.1，加入不同内核的 URL 支持。
