### ISSUE TITLE
Apple M处理器(arm64)安装异常无法打开App

### ISSUE THREAD

**Issue by Kia678** [keiko233/clash-nyanpasu#290]
### 复现步骤 / Step to reproduce

![image](https://github.com/keiko233/clash-nyanpasu/assets/85081567/bfe7f636-2380-4813-a270-8a4f9608d190)

### 预期行为 / Expected behaviour

正常应当在拖动到Applications之后，mac启动台中显示clash-nyanpasu图标

### 实际行为 / Actual Behaviour

在Apple M处理器下，无法安装到 Applications，启动台应用中心内也没有clash-nyanpasu图标，Applications打开显示应用已损坏

### 应用日志 / App logs

none

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.3

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

macOS 12.6

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请看 Readme。
