### ISSUE TITLE
安装包执行安装时只结束了GUI没结束内核进程

### ISSUE THREAD

**Issue by S-T-eve** [keiko233/clash-nyanpasu#291]
### 复现步骤 / Step to reproduce

在未关闭代理和GUI的情况下执行安装文件“Clash.Nyanpasu_1.4.3_x64-setup.exe”，安装程序只结束了GUI进程未结束内核，导致覆写错误提示，可能影响部分在GUI内更新执行安装的用户

### 预期行为 / Expected behaviour

GUI和内核一起结束进程，无阻碍的完成安装（部分以服务模式部署内核的可能需要由安装包临时禁用服务，安装完成后再尝试开启）

### 实际行为 / Actual Behaviour

![image](https://github.com/keiko233/clash-nyanpasu/assets/53549980/071a4d26-2d20-4447-9ee9-c0cc641a4ba1)

### Clash Nyapasu 版本号 / Clash Nyapasu

v1.4.3

### 是否为 Pre-release / Is pre-release version

latest

### 操作系统及版本 / OS version

Windows 10.0.19045.3803

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
这个需要我之后有空研究一下。我目前没研究过这种更新流程，以前写的 GUI 程序都是单独写一个 Updater 程序做更新的。类似 QQ 那种。

如果有研究方向的建议的话可以跟在此问题里。

**Comment by greenhat616** [comment]
我觉得应该需要自定义 WIX、NSIS 的模板才可以，有空改一下吧。

**Comment by yjplayerhyw** [comment]
![屏幕截图 2024-01-21 202928](https://github.com/keiko233/clash-nyanpasu/assets/21964839/db7c44e5-27bf-437f-897d-1bd6c805a63e)

无法导入订阅链接

**Comment by 5460** [comment]
今天1.4.3主界面左上角图标提示更新，点击更新后，更新程序把1.4.4装到C:\Program Files\Clash Nyanpasu下面了。原本在AppData那里的1.4.3还在，更新程序结束之后运行的也是这里的1.4.3版本。
看起来更新程序还需要完善一下。

**Comment by greenhat616** [comment]
> 今天1.4.3主界面左上角图标提示更新，点击更新后，更新程序把1.4.4装到C:\Program Files\Clash Nyanpasu下面了。原本在AppData那里的1.4.3还在，更新程序结束之后运行的也是这里的1.4.3版本。 看起来更新程序还需要完善一下。

准备 1.5.0 和隔壁 verge 一样，把 wix 砍了。只提供 nsis 了。

**Comment by greenhat616** [comment]
最新的开发版，你可以试一下。

**Comment by S-T-eve** [comment]
安装目录改了是吗，另外再次覆盖安装时依旧
![image](https://github.com/keiko233/clash-nyanpasu/assets/53549980/b49ef1da-49dd-48e4-9f94-d49e49d11b8a)
，要不干脆就弹窗提示用户手动正常方式关闭再执行安装？

**Comment by greenhat616** [comment]
> 安装目录改了是吗，另外再次覆盖安装时依旧 ![image](https://private-user-images.githubusercontent.com/53549980/302921649-b49ef1da-49dd-48e4-9f94-d49e49d11b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg5NjgsIm5iZiI6MTcwNzI5ODY2OCwicGF0aCI6Ii81MzU0OTk4MC8zMDI5MjE2NDktYjQ5ZWYxZGEtNDlkZC00OGU0LTlmOTQtZDQ5ZTQ5ZDExYjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA5Mzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYThhZDM0ZGZiYmJmMmFjNmUyMGFlOTY0NTQ2MTY5OTFjMmI1MzU5YWI1MWEzNTFhNDllYzAzMzJhMTQxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfIx10TL5OIn_uUXTIi2r3p4GgFEE_sqnldh3beHOaU) ，要不干脆就弹窗提示用户手动正常方式关闭再执行安装？

我等会修改成 Both 看看。我看看我的模板哪里写错了。

**Comment by greenhat616** [comment]
我知道了，得安装一次新版，之后的安装才会生效。你可以安装两次看看。

**Comment by greenhat616** [comment]
可以试新的开发构建版。
https://github.com/keiko233/clash-nyanpasu/actions/runs/7827742325

**Comment by S-T-eve** [comment]
确认可用，无问题
