### ISSUE TITLE
[Feature] 在Releases中提供macos_ aarch64架构构建版本

### ISSUE THREAD

**Issue by KyoSakuyo** [keiko233/clash-nyanpasu#3]
希望在Releases中提供macos_ aarch64架构构建版本

**Comment by keiko233** [comment]
aarch64 后续会添加支持，具体问题请看这里 https://github.com/keiko233/clash-nyanpasu/commit/a8c74e39c210d5259312fefea63e5a8f20ebab42

**Comment by dyxushuai** [comment]
如何做可以帮助这个issue

**Comment by keiko233** [comment]
我的mac正在维修，有兴趣可以自行编译测试提交PR

**Comment by dyxushuai** [comment]
> 我的mac正在维修，有兴趣可以自行编译测试提交PR

测试了一天没出现问题

**Comment by keiko233** [comment]
由于github actions不提供macos aarch64的镜像，还需要测试能否通过交叉编译，这需要一点时间

**Comment by dyxushuai** [comment]
> 由于github actions不提供macos aarch64的镜像，还需要测试能否通过交叉编译，这需要一点时间

我可以帮忙测试交叉编译

**Comment by keiko233** [comment]
> > 由于github actions不提供macos aarch64的镜像，还需要测试能否通过交叉编译，这需要一点时间
> 
> 我可以帮忙测试交叉编译

下次pre release会尝试构建，可以去那边下载到测试版本

**Comment by mo3et** [comment]
可以的话麻烦也试试Linux aarch64 版本

**Comment by keiko233** [comment]
> 可以的话麻烦也试试Linux aarch64 版本

![image](https://github.com/keiko233/clash-nyanpasu/assets/76520798/781a2428-c748-4d5c-b20c-bbe5b4ca3dd7)
https://tauri.app/v1/guides/building/cross-platform/

**Comment by keiko233** [comment]
macos aarch64 构建现已支持， 在这里下载到预发布版本 https://github.com/keiko233/clash-nyanpasu/releases/tag/dev

**Comment by iugo** [comment]
> macos aarch64 构建现已支持， 在这里下载到预发布版本 https://github.com/keiko233/clash-nyanpasu/releases/tag/dev

最新的预发版已经改为: https://github.com/keiko233/clash-nyanpasu/releases/tag/pre-release

**Comment by iugo** [comment]
@keiko233 预发版的内置更新应该存在问题, 因为 [latest.json](https://github.com/keiko233/clash-nyanpasu/releases/download/pre-release/latest.json) 没有相应变化.

**Comment by greenhat616** [comment]
> @keiko233 预发版的内置更新应该存在问题, 因为 [latest.json](https://github.com/keiko233/clash-nyanpasu/releases/download/pre-release/latest.json) 没有相应变化.

win 吗，这个是已知问题.得寻找 workaround.
如果是其他 OS 的话，应该是正常的. 更新器使用的地址为 https://github.com/keiko233/clash-nyanpasu/releases/download/updater/update-nightly.json
