### ISSUE TITLE
排除某些网站或 IP 不被代理

### ISSUE THREAD

**Issue by gitlayzer** [keiko233/clash-nyanpasu#304]
### 需求 / Requirement

我希望向 clash-for-windows 内的设置，系统代理中的绕过系统代理的域名/IP 的功能

### 建议实现 / Suggested implements

类似黑白名单功能

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.3

### 是否为 Pre-release / Is pre-release version

20bc733

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Duplicated by https://github.com/keiko233/clash-nyanpasu/issues/86。

系统代理的设置里有

**Comment by gitlayzer** [comment]
@greenhat616 当前这个功能并不太符合我的期望，还需要去修改订阅的配置文件，这个并不方便

**Comment by greenhat616** [comment]
他不是截图给你了么？https://github.com/keiko233/clash-nyanpasu/issues/86#issuecomment-1848094832

**Comment by gitlayzer** [comment]
@greenhat616 我换了 [clash-verge](https://github.com/clash-verge-rev/clash-verge-rev)，已经搞定这个问题了

**Comment by renhao12356578** [comment]
@gitlayzer 怎么解决的？求

**Comment by gitlayzer** [comment]
> [@gitlayzer](https://github.com/gitlayzer) 怎么解决的？求

换了软件 [clash-verge-rev](https://github.com/clash-verge-rev/clash-verge-rev)
