### ISSUE TITLE
[BUG] 关闭面板后从Windows托盘图标鼠标单击打开速度较慢，双击的速度正常

### ISSUE THREAD

**Issue by HeroTch** [keiko233/clash-nyanpasu#31]
**问题描述**
双击打开时界面有刷新动画，单击和 右键-> 打开面板 时没有动画效果 ，供参考

**Information**

- OS: Windows 11 23H2 22631.2715
- Clash Nyanpasu Version: 1.4.0
- Clash Core: Clash

**Comment by greenhat616** [comment]
![image](https://github.com/keiko233/clash-nyanpasu/assets/41122242/b88f6b16-76b0-4de4-9767-3144acf23472)

这个貌似是 verge 有意设计的延迟，为了防止 windows 上页面闪烁。但我不确定是不是这里。
有空的话，我可以再仔细调查下具体原因。

**Comment by greenhat616** [comment]
我们重新调查这个问题，已经修复双击开启速度异常的问题。
