### ISSUE TITLE
Portable 版本在 Win10 下无通知信息

### ISSUE THREAD

**Issue by zptan** [keiko233/clash-nyanpasu#314]
### 复现步骤 / Step to reproduce

导入订阅URL

### 预期行为 / Expected behaviour

导入失败时弹出相应的错误信息

### 实际行为 / Actual Behaviour

默默失败

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.3，1.4.4-alpha+23ced3b

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 10 22H2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Miracle-Sakuno** [comment]
请尽快删除你上传的文件，里面包含你的节点信息

**Comment by greenhat616** [comment]
你是不是打开了勿扰模式，导致通知无法通知？

**Comment by greenhat616** [comment]
无法复现，在不提供日记，且无任何其他条件补充的情况下，更倾向于系统设置问题。

**你可以尝试右下角那个控制中心图标，展开来看看喵帕斯的通知是否在里面，在的话，那就是系统设置的问题了。**


喵帕斯与 verge 的区别在于通知优先使用系统通知，在通知权限被拒绝的情况下使用网页的模态框进行通知。


Windows 10 上有个设置叫专注助手，这个选项等价于“勿扰模式”，你可以检查下这个选项有没有打开。

https://support.microsoft.com/zh-cn/windows/在特定时间关闭-windows-中的通知-81ed1b25-809b-741d-549c-7696474d15d3#ID0EDD=Windows_10

**Comment by greenhat616** [comment]
> > 你可以尝试右下角那个控制中心图标，展开来看看喵帕斯的通知是否在里面，在的话，那就是系统设置的问题了。
> 
> 确定没有打开静默模式
> 
> 打开log看到error，但是这个error没有在软件界面上显示
> 
> > 2024-01-23 20:19:03 ERROR - the remote profile data is invalid yaml
> 
> BTW，我使用的是portable版本，解压后直接用的，没有经过安装

确实有这个可能，稍晚我测试下 Portable 版本看看。通知权限可能需要通过注册表获取。

**Comment by greenhat616** [comment]
> 我使用clash-verge也是portable版本，能弹出错误信息

原理不一样的，上面解释过技术细节了，我们用的通知方式是系统通知，和 ntqq 的是一样的。

**Comment by greenhat616** [comment]
Portable 版本在干净的 Windows 10 下确实有这个问题。 Windows 11 上无法复现。

可能和这个问题有关系：https://support.microsoft.com/zh-cn/windows/%E5%9C%A8%E7%89%B9%E5%AE%9A%E6%97%B6%E9%97%B4%E5%85%B3%E9%97%AD-windows-%E4%B8%AD%E7%9A%84%E9%80%9A%E7%9F%A5-81ed1b25-809b-741d-549c-7696474d15d3#ID0EDD=Windows_10

等过几天忙完了，我再研究一下。目前你可以先使用安装版本测试一下。

**Comment by greenhat616** [comment]
我先禁用 Portable 版本下使用系统 notification 吧。
