### ISSUE TITLE
[Feature]建议换一个任务栏图标或者可以自定义任务栏图标，

### ISSUE THREAD

**Issue by QIU-XING** [keiko233/clash-nyanpasu#32]
任务栏图标相比其他的图标有点小，比其他的图标小了一号。
所以整体看起来就比较奇怪。
能不能换一个图标或者能够支持图标自定义，如和CFW一样支持自定义图标。

**Comment by keiko233** [comment]
大概率不会支持自定义图标，至于大小问题可能已经修复了 https://github.com/keiko233/clash-nyanpasu/commit/4015cb345b3e79f5504d826431406b53230105fd

**Comment by keiko233** [comment]
> > 大概率不会支持自定义图标，至于大小问题可能已经修复了 [4015cb3](https://github.com/keiko233/clash-nyanpasu/commit/4015cb345b3e79f5504d826431406b53230105fd)
> 
> 现在在release里的1.40版本还是没有修复的，请问新的版本什么时候更新？

最新pre release已更新
