### ISSUE TITLE
无法检测版本更新

### ISSUE THREAD

**Issue by Tefive** [keiko233/clash-nyanpasu#329]
### 复现步骤 / Step to reproduce

![屏幕截图 2024-01-26 111228](https://github.com/keiko233/clash-nyanpasu/assets/134689082/afa7a57b-1834-454f-8459-2d8d2fe3b7a7)

### 预期行为 / Expected behaviour

我多个版本都无法检测到版本更新，1.4.2和1.4.3已经1.4.4点击更新都提示没有可用更新

### 实际行为 / Actual Behaviour

点击更新应找到可用更新

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.4

### 是否为 Pre-release / Is pre-release version

略

### 操作系统及版本 / OS version

windows 10

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
你在使用最新的版本，怎么可能检测到更新的更新呢？

**Comment by Tefive** [comment]
我在低版本也无法检测到新版本更新

**Comment by greenhat616** [comment]
最新的版本是 1.4.3，和 dev 是两个频道，也不可能检测到 1.4.4。如果你想说的 1.4.2 无法更新 1.4.3，请提供日记和截图。

**Comment by Tefive** [comment]
![屏幕截图 2024-01-29 123656](https://github.com/keiko233/clash-nyanpasu/assets/134689082/001d902b-5231-45c6-9dcb-5f6c592fdc61)

**Comment by greenhat616** [comment]
已修复

**Comment by Tefive** [comment]
多谢大佬，已经可以看到更新提示了

**Comment by Tefive** [comment]
https://github.com/keiko233/clash-nyanpasu/assets/134689082/b38a6659-c898-4c4f-bbba-baae7b190e80

但是大佬目前又有新的问题，选择更新后会自动重新安装一个新版本，默认安装在C:\Program Files\Clash Nyanpasu这个位置，是否可以和别的软件一样覆盖安装，这是录屏
