### ISSUE TITLE
无法正确调用外部exe（enableloopback.exe installer.exe）

### ISSUE THREAD

**Issue by GYF0814** [keiko233/clash-nyanpasu#351]
### 复现步骤 / Step to reproduce

打开uwp工具或安装服务模式均会出现

https://github.com/keiko233/clash-nyanpasu/assets/88437660/f6fee6bc-d0f3-49cb-a23f-c31fc37e0425

### 预期行为 / Expected behaviour

应该正常打开exe

### 实际行为 / Actual Behaviour

![Clip_20240131_114908](https://github.com/keiko233/clash-nyanpasu/assets/88437660/294cf362-1c88-42d6-8307-066deb680664)

### 应用日志 / App logs

2024-01-31 11:50:58 ERROR - failed to connect to the Clash Nyanpasu Service
2024-01-31 11:51:02 ERROR - failed to connect to the Clash Nyanpasu Service
2024-01-31 11:51:04 ERROR - installer exe not found
2024-01-31 11:51:06 ERROR - failed to connect to the Clash Nyanpasu Service

### 备注 / Addition details

gui真的很好看awawawaw薄纱verge

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.4

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

Windows 10 企业版 21H2 19044.3086

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
https://github.com/keiko233/clash-nyanpasu/actions/runs/7725283319
等这个 CI 跑好了，试一下 pre-release
