### ISSUE TITLE
更新1.4.4时不能更改mihomo.exe

### ISSUE THREAD

**Issue by zhongjie10086** [keiko233/clash-nyanpasu#364]
### 复现步骤 / Step to reproduce

旧软件是1.4.2的情况下，下载GitHub里的1.4.4版本进行更新，在开了管理员权限运行更新时依然出现，如图
<img width="320" alt="%7B66AAF94F-9A9E-4091-B273-94C4B5C85253%7D" src="https://github.com/keiko233/clash-nyanpasu/assets/48387208/9799eee1-6358-4421-92bd-76d330167915">

### 预期行为 / Expected behaviour

预期正常更新

### 实际行为 / Actual Behaviour

实际会出错，需要忽略它

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Duplicated by https://github.com/keiko233/clash-nyanpasu/issues/291
