### ISSUE TITLE
[Feature] 添加tun模式指示托盘图标

### ISSUE THREAD

**Issue by Kuingsmile** [keiko233/clash-nyanpasu#37]
在tun模式启动时，托盘图标改变颜色进行指示，类似系统代理启动时切换为粉色猫猫，tun模式或许用个紫色？

**Comment by keiko233** [comment]
可以哦，但是紫色可能不太好看（现在的粉色争议也挺大），深蓝或者浅蓝应该会更好一点

**Comment by Kuingsmile** [comment]
嗯嗯 颜色可以选 主要有个指示作用

**Comment by sxnpu** [comment]
原先cfw的黄色、蓝色看着挺顺眼的，应该比较符合大多数人审美

**Comment by keiko233** [comment]
![image](https://github.com/keiko233/clash-nyanpasu/assets/76520798/4d5dfe36-d3f9-4afb-8a99-f1d2b7352ec5)
![image](https://github.com/keiko233/clash-nyanpasu/assets/76520798/d21229b5-05c4-4974-b0d5-e8b873c00458)

done. https://github.com/keiko233/clash-nyanpasu/commits/dev/
