### ISSUE TITLE
软件更新时会在默认位置安装，而不是安装在首次安装时指定的位置

### ISSUE THREAD

**Issue by PRO-2684** [keiko233/clash-nyanpasu#415]
### 复现步骤 / Step to reproduce

1. 安装 Clash Nyanpasu v1.4.4，更改默认的安装目录（例如改到 D 盘）
2. 打开 Clash Nyanpasu，收到更新提示
3. 点击“更新”按钮，按照引导完成更新

### 预期行为 / Expected behaviour

老版本被卸载，新版本自动安装在老版本选定的位置；或者更新程序提供选择安装路径的选项

### 实际行为 / Actual Behaviour

更新程序并未提供选择安装路径的选项，而是直接安装在 C 盘的默认安装路径下，导致电脑上同时存在两个 Clash Nyanpasu，一个是安装在 D 盘的老版本，另一个是安装在 C 盘的新版本

### 备注 / Addition details

由于使用最新版就无法检测到更新，并且 release notes 中并未提到相关的修复，故未使用最新版/Pre-release 进行测试。

### Clash Nyapasu 版本号 / Clash Nyapasu

v1.4.4

### 是否为 Pre-release / Is pre-release version

N/A

### 操作系统及版本 / OS version

Windows 11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
这是预期行为，更新日记里面有BC。
