### ISSUE TITLE
[Feature]clash meta已恢复更新 希望开发者尽快更新内核

### ISSUE THREAD

**Issue by MisakaOne** [keiko233/clash-nyanpasu#45]
项目名已更改为mihomo
Binary file name changes to mihomo, along with most of the const such as default config path, check and update these file/path before update to this version.
项目地址为https://github.com/MetaCubeX/mihomo/releases

**Comment by greenhat616** [comment]
duplicated by https://github.com/keiko233/clash-nyanpasu/issues/20 https://github.com/keiko233/clash-nyanpasu/pull/30

请等待 dev 分支发布

**Comment by keiko233** [comment]
已经默认内嵌1.17.0了哦，前往pre release下载即可食用

**Comment by lainbo** [comment]
> 已经默认内嵌1.17.0了哦，前往pre release下载即可食用

pre-release里面的是1.4.0,这个版本里面的是1.16.0的内核~是我没有找到地方吗?
还有一个小问题就是`update-proxy.json`里面的ghproxy已经无法从中国大陆访问了，被GFW封了，新的站点是[mirror.ghproxy.com](https://mirror.ghproxy.com/)

感谢大佬的付出

**Comment by greenhat616** [comment]
@lainbo dev 构建：https://github.com/keiko233/clash-nyanpasu/releases/tag/dev

注：开发版本已经添加了新的源：https://github.com/keiko233/clash-nyanpasu/commit/11ae5ef4a9d94fe5c812c11a65b2ed8e667a9dc4#diff-7b5f5e4e72a6bf655ee5f197615575d1d74dd5aecf8f221f0b37ded88a3223a3
