### ISSUE TITLE
[Feature] Add support for the clash kernel, which is still being maintained.

### ISSUE THREAD

**Issue by 2926295173** [keiko233/clash-nyanpasu#5]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

Currently, [this repository](https://github.com/MerlinKodo/clash-rev) is still being maintained, so I hope we can add an extra item in the Settings -> Clash Kernel menu to use this clash kernel.

**Describe alternatives you've considered**

none
**Additional context**

none

**Comment by keiko233** [comment]
LGTM, may support in future

**Comment by lux5am** [comment]
it's closed now thanks to you
