### ISSUE TITLE
[Feature]是否能够支持像ClashForWindows那样的预处理配置功能

### ISSUE THREAD

**Issue by yonee77** [keiko233/clash-nyanpasu#50]
是否能够支持像ClashForWindows那样的预处理配置功能,个性化分流很需要,谢谢

**Comment by greenhat616** [comment]
[![image](https://github.com/keiko233/clash-nyanpasu/assets/41122242/82c4df6f-1e1b-4c95-89c7-5f69339f5e07)
](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)

https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#script-%E8%84%9A%E6%9C%AC%E5%A4%84%E7%90%86
