### ISSUE TITLE
script覆写处理，main(params)和main(config)有区别吗

### ISSUE THREAD

**Issue by deuteros-gex** [keiko233/clash-nyanpasu#52]
确实不懂rust和js，所以是把
https://github.com/keiko233/clash-nyanpasu/blob/9e2ae311cd47f7b6fb60e77283955b21c9bbb846/src-tauri/src/enhance/script.rs#L5
丢给AI去读的。没理解错的话，应该是：

 **把yaml格式的clash config文件用serde_json转成javascript对象，然后用quickJS创建一个无特殊设置或context的runtime跑起用户js脚本，把上述javascript对象丢给这个脚本去处理。
 具体的文本处理功能完全由用户js脚本赋予，基本当成模块化黑盒来用就行。**

粗线条的逻辑挺好懂，但是填充细节时就有点抓瞎了。哪怕是作者自己提供的实例中，声明main函数也出现了两种写法
[main(params)](https://github.com/zzzgydi/clash-verge/issues/520) 
[main(config)](https://github.com/zzzgydi/clash-verge/issues/183#issuecomment-1238159464)

但我看下来，上面两种写法并没体现出什么区别，甚至互换都可以？那么main函数还允许其他声明方式吗？

可能有点啰嗦，不少表述也不太准确。。但个人觉得既然目前的现状是[需求稍微复杂点就得上script](https://github.com/zzzgydi/clash-verge/issues/174)的话，那script功能的解释到[subconverter那种程度](https://github.com/tindy2013/subconverter/blob/master/README-cn.md?plain=1#L514)才足够指导使用，它介绍脚本写法时也没多少字，无非是函数声明允许的具体写法，以及入参的node具体长啥样。
剩下都是纯粹javascript语法，问AI都行了。

**Comment by greenhat616** [comment]
JS 这边只关心你的函数（Function）接受几个参数，举个例子：
```js
function A(a) { console.log(a) }
function B(b) { console.log(b) }
const C = (c) => console.log(c)

const data= { a: 1 }
A(data)
// output: { a: 1 }
B(data)
// output: { b: 1 }
C(data)
// output: { b: 1 }
```
你想叫什么都随意，这不是 Python，Swift 那种 `fn(a=x)` 的命名参数。


Script 的用法（目前），说白就是让你在一个 JS 上下文里，创建一个名为 main 的方法（函数），他会这么使用这个方法（简化）：
```ts
const config = xxxx;  // config 来自 Rust 后端注入
const output = main(config)
```

**Comment by deuteros-gex** [comment]
非常感谢，确实是我想多了。~~main(MAGA)也不是不行~~

**Comment by li-chunyuan** [comment]
大家好，占楼礼貌问一下我的问题，我算是一个新手小白。想请教一下，如何使用Clash Verge配置链式代理?


我现在使用clash verge ，购买了机场的订阅链接，能正常访问外网。但是因为对静态住宅IP的需求，特意买了个静态住宅IP。


我现在发现使用merge文件覆写扩展没用，无法搭建成链式代理。请问，怎么样可以呢？需要用的全局扩展脚本吗
