### ISSUE TITLE
[BUG]1.4.1 升级后托盘中的猫猫图标是白色的吗，上一版本是粉色，然后cmd无法代理

### ISSUE THREAD

**Issue by ningsibuqu** [keiko233/clash-nyanpasu#55]
![image](https://github.com/keiko233/clash-nyanpasu/assets/51028975/6c856278-d26e-4029-a80b-d399b5ec92cb)
1.4.1

![image](https://github.com/keiko233/clash-nyanpasu/assets/51028975/6c1d91d5-35d5-4aeb-9282-34fc9ea5873a)
1.4.0

**Comment by how1ewu** [comment]
你把系统代理打开就是粉色的了

**Comment by mixwind-1** [comment]
我也是没变色，而且托盘中的图标很丑，怎么换啊？

**Comment by dogpem** [comment]
> 你把系统代理打开就是粉色的了

实测更新到 v1.4.1后打开系统代理不会变粉色
![image](https://github.com/keiko233/clash-nyanpasu/assets/115675753/d4dfc2c9-3819-484d-9be0-44dc1c7b4318)

**Comment by greenhat616** [comment]
已确认。这是由图标为非标准 RGBA PNG导致的。这会在 https://github.com/keiko233/clash-nyanpasu/pull/65 修复。

**Comment by ningsibuqu** [comment]
> 你使用了拨号连接之类的方式吗？
> 
> ![image](https://private-user-images.githubusercontent.com/41122242/288401932-7544cc8d-5f27-4586-9a2a-8da2f206230c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjMyMDgsIm5iZiI6MTcwMjAyMjkwOCwicGF0aCI6Ii80MTEyMjI0Mi8yODg0MDE5MzItNzU0NGNjOGQtNWYyNy00NTg2LTlhMmEtOGRhMmYyMDYyMzBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4MDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4OTE0NTdjNDBiYTM0NzQ0ZGI1ODFhOGUzMjUwMmRlM2Y0NDVmOTg5NjllZDZjYWQ3NWU2OGFkMGQwZDkzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Sku8JcZ6ALL6RoH69zuJOMqiV65oy4lwrMWtzurhAU)
> 
> 实际上测试（无拨号连接）是可以实际修改系统代理配置的。 你在 CMD 里使用的什么程序无法代理呢（有尝试过重新开关终端么）？
> 
> @mixwind-1 @ningsibuqu 图标的问题等 @keiko233 回复吧🎈
