### ISSUE TITLE
[BUG]无法记住调整的软件窗口大小

### ISSUE THREAD

**Issue by aawwsslll** [keiko233/clash-nyanpasu#56]
不知道这算不算bug, 每次重启后打开都是很小的窗口模式(2K屏幕)，
希望可以记住上次调整的窗口大小，版本最新版，系统最新版win11预览版。

**Comment by greenhat616** [comment]
Dev 构建已经可用：https://github.com/keiko233/clash-nyanpasu/releases/tag/dev
