### ISSUE TITLE
[Feature] 希望增加authentication配置

### ISSUE THREAD

**Issue by Y4er** [keiko233/clash-nyanpasu#58]
希望增加authentication认证账号密码配置选项

**Comment by Y4er** [comment]
给clash.meta提了pr https://github.com/MetaCubeX/mihomo/pull/885

clash-nyanpasu画个界面增加个api请求应该就可以了，等下一版希望可以有这个功能。

**Comment by greenhat616** [comment]
目前是，不能通过配置文件修改使用这个功能嘛

**Comment by greenhat616** [comment]
> 现在只能通过重新编辑配置文件来使用这个功能，但是订阅更新的时候会覆盖掉authentication配置。

可以使用 Merge 或者 Script 功能来解决这个问题。在 CFW 里，有个类似的功能叫做 Mixin。
