### ISSUE TITLE
[Feature]希望能修一下拨号环境下代理无法开启的问题

### ISSUE THREAD

**Issue by moranno** [keiko233/clash-nyanpasu#6]
当使用拨号网络的时候代理无法正常开启

参考
https://myth.cx/p/windows-proxy/

https://github.com/zzzgydi/clash-verge/issues/833

**Comment by keiko233** [comment]
emmmmm，看上去我需要一点时间去了解相关内容

**Comment by greenhat616** [comment]
@keiko233 https://github.com/zzzgydi/sysproxy-rs/pull/3 按 c 的 sysproxy 实现了。但是没有测试存在 PPPOE 这种 interface 的时候的情况（`Ras` 那个分支），我目前没有这类的设备。

如果需要集成的话，是直接指定 git hash，还是说直接拆成 workspace。

**Comment by keiko233** [comment]
> @keiko233 [zzzgydi/sysproxy-rs#3](https://github.com/zzzgydi/sysproxy-rs/pull/3) 按 c 的 sysproxy 实现了。但是没有测试存在 PPPOE 这种 interface 的时候的情况（`Ras` 那个分支），我目前没有这类的设备。
> 
> 如果需要集成的话，是直接指定 git hash，还是说直接拆成 workspace。

如果repo作者不合并pr的话我觉得作为workspace是个更好的选择

**Comment by greenhat616** [comment]
那我先修改为workspace 吧。之后再 draft 个 pr，加一下 lint 以及 deps 自动更新？

**Comment by keiko233** [comment]
> 那我先修改为workspace 吧。之后再 draft 个 pr，加一下 lint 以及 deps 自动更新？

当然可以

**Comment by greenhat616** [comment]
您好，修复补丁已合并进去了。可以尝试 dev 构建，看看拨号情况下是否能正常使用。https://github.com/keiko233/clash-nyanpasu/releases/tag/dev

**Comment by xinye0123** [comment]
1.6.1 版本 又不行了哎 没有设置拨号的代理
