### ISSUE TITLE
希望添加 macos使用tun模式可以自动修改dns 功能

### ISSUE THREAD

**Issue by xingyue52077** [keiko233/clash-nyanpasu#60]
在mac上使用tun模式时每次要手动修改dns 192.168.0.2，希望可以添加自动修改功能。

**Comment by greenhat616** [comment]
Got supported in v1.4.2.

**Comment by wycivil08** [comment]
Hey there,

Just noticed on MacOS 14.3, this completed issue are popping back up. Can anybody check it out ?
Thanks!
