### ISSUE TITLE
[Feature]更新订阅不覆盖修该的内容 增加类似 Diff的功能

### ISSUE THREAD

**Issue by iKun10001** [keiko233/clash-nyanpasu#63]
大佬求增加一个diff的功能哇```

**Comment by greenhat616** [comment]
1. diff 或者叫 Merge 的功能，已有。重复：https://github.com/keiko233/clash-nyanpasu/issues/52 https://github.com/keiko233/clash-nyanpasu/issues/58 https://github.com/keiko233/clash-nyanpasu/issues/50 https://github.com/keiko233/clash-nyanpasu/issues/40 
2. 窗口大小问题，你可以新开个问题。等我或者其他人闲下来的话，可以加。
