### ISSUE TITLE
[BUG]1.4.1 启用抖音录制工具的时候 报错 请求网页失败,请检查是否用了代理

### ISSUE THREAD

**Issue by ningsibuqu** [keiko233/clash-nyanpasu#81]
1.4.0 无报错

1.4.1 不知怎么自动走了代理导致报错？

序号0 网址内容获取失败,进行重试中...获取失败的地址是:https://live.douyin.com/69416429589 请求网页失败,请检查是否用了代理,错误信息: HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: /webcast/room/web/enter/?aid=6383&device_platform=web&cookie_enabled=true&browser_language=zh-CN&browser_platform=Win32&browser_name=Chrome&browser_version=100.0.4896.127&web_rid=232031876020 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))) 发生错误的行数: 343

现在临时的解决方法是在系统代理设置 Proxy Bypass 中加入 *.douyin.com;

**Comment by ningsibuqu** [comment]
> Clash 核心的规则没给这个规则放行？ 看其实这个工具是 Python 写的？不太像是风控的问题。

1.4.0 的 内核和 1.4.1 一致吧 就是改了个名而已？

**Comment by greenhat616** [comment]
1.4.1 换了 1.17.0 Meta 改名后的内核
