### ISSUE TITLE
[Feature]希望可以增加Parsers和Bypass功能

### ISSUE THREAD

**Issue by Maozai-Teng** [keiko233/clash-nyanpasu#86]
如题，希望增加Parsers和Bypass功能，这两个是我在Clash for Windows最常用的功能了。
一个是配置文件预处理Parsers，可以自定义规则，让规则更适合自己的用法，并防止机场的更新导致覆盖，让软件使用更得心应手。
![image](https://github.com/keiko233/clash-nyanpasu/assets/18625640/b69d0db0-c278-4f0f-8515-412ddef8b855)
![image](https://github.com/keiko233/clash-nyanpasu/assets/18625640/49056ff0-51f1-44b1-82fb-975196015c26)

另一个是规则绕过Bypass，我是会把大多数的国内网站和不希望走梯子的全部写这里面，直接不走内核，增加自定义的同时也让软件负担减轻，使用更舒心。
![image](https://github.com/keiko233/clash-nyanpasu/assets/18625640/de47358b-bba3-4cf8-9bab-f58779c0a9f4)
![image](https://github.com/keiko233/clash-nyanpasu/assets/18625640/2c2786df-e5d1-46ae-9910-5551646eed07)

希望作者可以评估一下然后加上这两个非常好用的功能，最后也非常感谢作者接过接力棒，软件越做越好~

**Comment by RESTART1230** [comment]
![image](https://github.com/keiko233/clash-nyanpasu/assets/59726731/e175fc99-72fa-4002-a64f-94eebd23e13c)
![image](https://github.com/keiko233/clash-nyanpasu/assets/59726731/5c720208-f6c1-46df-bae8-1469aee5f1fd)

**Comment by greenhat616** [comment]
1. 配置预处理可以用 Merge 或者 script 功能。
1. bypass 是系统代理的 bypass 还是 clash 内核的 bypass？如果说系统代理的，已经有了。

**Comment by Maozai-Teng** [comment]
> 1. 配置预处理可以用 Merge 或者 script 功能。
> 2. bypass 是系统代理的 bypass 还是 clash 内核的 bypass？如果说系统代理的，已经有了。

大佬你好，bypass我找到了，预处理的这个merge和script功能在哪里，我没找到，可否详细介绍一下，谢谢了~

**Comment by greenhat616** [comment]
https://github.com/keiko233/clash-nyanpasu/issues/63#issuecomment-1846447256

**Comment by Maozai-Teng** [comment]
> [#63 (comment)](https://github.com/keiko233/clash-nyanpasu/issues/63#issuecomment-1846447256)

收到，谢谢！
我看了“https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#script-%E8%84%9A%E6%9C%AC%E5%A4%84%E7%90%86”里面的教程~
不过好像稍微有点难超纲了QAQ，我直接把之前CFW里面写好的Parsers参数复制粘贴过去，不管是merge和script都运行不了。
（我的设定是完全删掉订阅里面除节点之外的全部设置，然后自己全部覆写proxy-groups，rules和rule-providers）
希望能单独提取出来做成一个模块功能，就像CFW那样子=。=

**Comment by Maozai-Teng** [comment]
> > > [#63 (comment)](https://github.com/keiko233/clash-nyanpasu/issues/63#issuecomment-1846447256)
> > 
> > 
> > 收到，谢谢！ 我看了“[https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#script-%E8%84%9A%E6%9C%AC%E5%A4%84%E7%90%86”里面的教程](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#script-%E8%84%9A%E6%9C%AC%E5%A4%84%E7%90%86%E2%80%9D%E9%87%8C%E9%9D%A2%E7%9A%84%E6%95%99%E7%A8%8B)~ 不过好像稍微有点难超纲了QAQ，我直接把之前CFW里面写好的Parsers参数复制粘贴过去，不管是merge和script都运行不了。 （我的设定是完全删掉订阅里面除节点之外的全部设置，然后自己全部覆写proxy-groups，rules和rule-providers） 希望能单独提取出来做成一个模块功能，就像CFW那样子=。=
> 
> 你可以考虑开个 Feature Request issue。但最多扩展 Merge 的移除功能。 事实上 CFW 的 Merge，Script 是支持切换的。因此设计上是比 CFW 好用的，你可以稍微了解下。

哦哦~所以因为现在merge没有移除功能，我之前的代码才不能直接移植过来用是吗？(⊙ｏ⊙)
我之所以这样设计先移除再全部重写是因为，各个鸡场的规则不一样，有的好用有的不好用。我直接全部干掉换成我自己的，这样子不管是什么订阅，最后都能按照我的规则来走，就非常舒服了~

我的移除和重建代码如下：

# - reg: ^.*$ 匹配所有订阅，或  - url: https://example.com/profile.yaml 指定订阅
  - reg: ^.*$
  # 删除服务商提供的策略组和规则
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const groups = []
        const rules = []
        return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
      } 
  # 建立自己的配置
    yaml:
      prepend-proxy-groups: # 建立策略组
        - name: ✈️ 代理模式
          type: select

        - name: 🔰 自动选择
          type: url-test #load-balance/url-test/fallback
          strategy: consistent-hashing # consistent-hashing / round-robin
          url: http://www.gstatic.com/generate_204
          interval: 600
          tolerance: 50

      commands:
        - proxy-groups.✈️ 代理模式.proxies=[]proxyNames|^((?!呐呐呐).)*$ # 向指定策略组添加订阅中的节点名，可使用正则过滤
        - proxy-groups.✈️ 代理模式.proxies.0+🔰 自动选择
        - proxy-groups.🔰 自动选择.proxies=[]proxyNames|^((?!呐呐呐).)*$

**Comment by Maozai-Teng** [comment]
> > > [#63 (comment)](https://github.com/keiko233/clash-nyanpasu/issues/63#issuecomment-1846447256)
> > 
> > 
> > 收到，谢谢！ 我看了“[https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#script-%E8%84%9A%E6%9C%AC%E5%A4%84%E7%90%86”里面的教程](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#script-%E8%84%9A%E6%9C%AC%E5%A4%84%E7%90%86%E2%80%9D%E9%87%8C%E9%9D%A2%E7%9A%84%E6%95%99%E7%A8%8B)~ 不过好像稍微有点难超纲了QAQ，我直接把之前CFW里面写好的Parsers参数复制粘贴过去，不管是merge和script都运行不了。 （我的设定是完全删掉订阅里面除节点之外的全部设置，然后自己全部覆写proxy-groups，rules和rule-providers） 希望能单独提取出来做成一个模块功能，就像CFW那样子=。=
> 
> 你可以考虑开个 Feature Request issue。但最多扩展 Merge 的移除功能。 事实上 CFW 的 Merge，Script 是支持切换的。因此设计上是比 CFW 好用的，你可以稍微了解下。

哦哦~所以因为现在merge没有移除功能，我之前的代码才不能直接移植过来用是吗？(⊙ｏ⊙)
我之所以这样设计先移除再全部重写是因为，各个鸡场的规则不一样，有的好用有的不好用。我直接全部干掉换成我自己的，这样子不管是什么订阅，最后都能按照我的规则来走，就非常舒服了~

我的移除和重建代码如下：

# - reg: ^.*$ 匹配所有订阅，或  - url: https://example.com/profile.yaml 指定订阅
  - reg: ^.*$
  # 删除服务商提供的策略组和规则
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const groups = []
        const rules = []
        return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
      } 
  # 建立自己的配置
    yaml:
      prepend-proxy-groups: # 建立策略组
        - name: ✈️ 代理模式
          type: select

        - name: 🔰 自动选择
          type: url-test #load-balance/url-test/fallback
          strategy: consistent-hashing # consistent-hashing / round-robin
          url: http://www.gstatic.com/generate_204
          interval: 600
          tolerance: 50

      commands:
        - proxy-groups.✈️ 代理模式.proxies=[]proxyNames|^((?!呐呐呐).)*$ # 向指定策略组添加订阅中的节点名，可使用正则过滤
        - proxy-groups.✈️ 代理模式.proxies.0+🔰 自动选择
        - proxy-groups.🔰 自动选择.proxies=[]proxyNames|^((?!呐呐呐).)*$
