### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Amazon90** [keiko233/clash-nyanpasu#9]
This looks like Clash Verge. I know a core Clash Rev that is currently being updated, and developers may consider supporting it.

**Comment by sf467** [comment]
Clash Rev 已经归档了，原因未知

**Comment by MerlinKodo** [comment]
由于meta内核改名虚空终端之后还在持续更新 所以我将clash rev归档了，没有必要重复开发分裂社区

**Comment by sf467** [comment]
> 由于meta内核改名虚空终端之后还在持续更新 所以我将clash rev归档了，没有必要重复开发分裂社区

可是大佬，meta内核仍然是归档状态啊，关于meta最近的更新也只有文档在5号的一次补充

**Comment by sf467** [comment]
> 由于meta内核改名虚空终端之后还在持续更新 所以我将clash rev归档了，没有必要重复开发分裂社区

可是大佬，meta内核仍然是归档状态啊，关于meta最近的更新也只有文档在5号的一次补充

**Comment by sf467** [comment]
> 由于meta内核改名虚空终端之后还在持续更新 所以我将clash rev归档了，没有必要重复开发分裂社区

谢谢你，小黑子
