### ISSUE TITLE
clash verge配置导入到Clash Nyanpasu的问题

### ISSUE THREAD

**Issue by 0Tune** [keiko233/clash-nyanpasu#90]
感觉Clash Nyanpasu更好用，于是从verge换到Nyanpasu来，但是发现我覆盖配置之后，Clash Nyanpasu任务栏的图标在开启系统代理之后不会变颜色了，请问正确导入方式应该是怎么样的，或者是各个模式的任务栏图标在哪修改呢？

**Comment by xsycyan** [comment]
我的也是，任务栏图标代理开和关都是小白猫。

**Comment by 0Tune** [comment]
您也是导入verge的配置的吗？在 2023年12月9日，上午11:04，西瓜啵啵 ***@***.***> 写道：﻿
我的也是，任务栏图标代理开和关都是小白猫。

**Comment by xsycyan** [comment]
我的没有导入配置，我是之前用的clashverge-portable，然后删掉了，然后下了nyanpasu1.4.1的portable版本，开关不会变色。
我又试了下1.4.0的，打开可代理以正常变小粉猫。

**Comment by 0Tune** [comment]
那有可能是这个版本的问题，我看这个有个预发布的nyanpasu，待会我试一下行不行在 2023年12月9日，上午11:11，西瓜啵啵 ***@***.***> 写道：﻿
我的没有导入配置，我是之前用的clashverge-portable，然后删掉了，然后下了nyanpasu1.4.1的portable版本，开关不会变色。
我又试了下1.4.0的，打开可代理以正常变小粉猫。

**Comment by fyhzc** [comment]
去试试最新开发版，dev

**Comment by greenhat616** [comment]
#55 开发版已修复。稳定版已确认这个问题。
