### ISSUE TITLE
[BUG]关于热键设置相关问题

### ISSUE THREAD

**Issue by Soniceso** [keiko233/clash-nyanpasu#96]
**Describe the bug**
可能和热键保存方式有关，以用F1作为绑定热键为例。在我没有对F1进行任何绑定的情况下，我可以用F1绑定所有的功能，并且可以成功保存，虽然只会生效一个，这是一点。
![image](https://github.com/keiko233/clash-nyanpasu/assets/10915608/120bfec1-73ba-48c4-adc8-66fc5f6fe5c1)
第二点，还是以F1为例，比如我在之前将F1设置为了打开面板，我现在F1想换成切换模式，我必须要先进入热键设置，清空打开面板的绑定，然后保存，再进入热键设置，绑定。如果只是在第一次打开热键设置清空F1的热键绑定，这个时候的F1是无法被设置的。
第三点，在数字键区上用数字1键作为热键进行绑定，但数字区绑定的1并不会被触发，需要用主键盘区的数字键1才可以触发。

**Information**

- OS: WIN11
- Clash Nyanpasu Version: 1.4.1
- Clash Core:  Clash Meta

**Additional context**
问题可能有些刁钻，应该是bug吧？

**Comment by greenhat616** [comment]
1、2 已修复，请等待开发分支发布。
3 是 Tauri 的问题，请等待上游修复：https://github.com/tauri-apps/tauri/issues/7543

**Comment by greenhat616** [comment]
https://github.com/tauri-apps/global-hotkey/issues/48

数字键这个问题，应该在 Tauri v2，或者使用 Tauri 维护的独立 crate 支持。
